# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'CC'), ('CE', 'CE'), ('TI', 'TI')], max_length=3)),
                ('numero_documento', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
    ]
