# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ref', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=30)),
                ('talla', models.CharField(max_length=3)),
                ('precio', models.FloatField()),
                ('foto', models.ImageField(upload_to='productos')),
            ],
        ),
    ]
