# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20160528_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=30, verbose_name='jajaja'),
        ),
    ]
