# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='contraseña',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
