# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160530_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='contraseña',
            field=models.CharField(max_length=50),
        ),
    ]
