# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='registrar',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
